# Generated by Django 6.0.2 on 2026-03-03 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('cultural', 'Cultural'), ('sports', 'Sports'), ('other', 'Other')], default='technical', max_length=20)),
                ('event_type', models.CharField(choices=[('solo', 'Solo Only'), ('group', 'Group Only'), ('both', 'Solo & Group')], default='both', max_length=10)),
                ('registration_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_participants', models.PositiveIntegerField(default=100)),
                ('upi_id', models.CharField(default='college@upi', help_text='UPI ID students should pay to', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('participation_type', models.CharField(choices=[('solo', 'Solo'), ('group', 'Group')], default='solo', max_length=10)),
                ('group_name', models.CharField(blank=True, max_length=200)),
                ('member_names', models.TextField(blank=True, help_text='Comma-separated member names (for group)')),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='payments/%Y/%m/')),
                ('payment_status', models.CharField(choices=[('not_uploaded', 'Not Uploaded'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_uploaded', max_length=20)),
                ('payment_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('unique_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at'],
                'unique_together': {('student', 'event')},
            },
        ),
    ]
